# Generated by Django 6.0.6 on 2026-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('author', models.CharField(max_length=255, verbose_name='Autorzy')),
                ('topic', models.CharField(max_length=255, verbose_name='Tematyka')),
                ('size_class', models.CharField(choices=[('small', 'mała'), ('medium', 'średnia'), ('large', 'duża'), ('very_large', 'bardzo duża')], max_length=20, verbose_name='Klasa wielkości')),
                ('download_link', models.URLField(verbose_name='Link do danych')),
                ('description', models.TextField(max_length=2000, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Próbka Bazy Danych',
                'verbose_name_plural': 'Próbki Baz Danych',
                'ordering': ['name'],
            },
        ),
    ]
