# Generated by Django 6.0.6 on 2026-06-25 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesample',
            name='complexity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Skomplikowanie (liczba tabel)'),
        ),
        migrations.AddField(
            model_name='databasesample',
            name='ddl_file',
            field=models.FileField(blank=True, null=True, upload_to='ddl/', verbose_name='Skrypt DDL'),
        ),
        migrations.AddField(
            model_name='databasesample',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AddField(
            model_name='databasesample',
            name='schema_image',
            field=models.ImageField(blank=True, null=True, upload_to='schemas/', verbose_name='Schemat (obraz)'),
        ),
    ]
